apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pinky-pipeline
  labels:
    app.kubernetes.io/name: pinky
spec:
  params:
  - name: repo-url
    type: string
  - name: image-ref
    type: string
  workspaces:
  - name: shared-workspace
  tasks:
  - name: git-clone
    taskRef:
      name: git-clone
      kind: ClusterTask
    params:
    - name: url
      value: $(params.repo-url)
    workspaces:
    - name: output
      workspace: shared-workspace
  - name: build
    taskRef:
      name: npm
      kind: ClusterTask
    runAfter:
    - git-clone
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: test
    taskRef:
      name: npm
      kind: ClusterTask
    runAfter:
    - build
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: image-build
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
    - test
    params:
    - name: IMAGE
      value: $(params.image-ref)
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: image-push
    taskRef:
      name: buildah
      kind: ClusterTask
    runAfter:
    - image-build
    params:
    - name: IMAGE
      value: $(params.image-ref)
    - name: PUSH_EXTRA_ARGS
      value: --digestfile /tmp/digest
    workspaces:
    - name: source
      workspace: shared-workspace
  - name: deploy
    taskRef:
      name: kubernetes-actions
      kind: ClusterTask
    runAfter:
    - image-push
    params:
    - name: script
      value: kubectl rollout restart deployment/pinky
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pinky-pipeline-run-
  labels:
    app.kubernetes.io/name: pinky
spec:
  pipelineRef:
    name: pinky-pipeline
  params:
  - name: repo-url
    value: https://github.com/alimobrem/pinky
  - name: image-ref
    value: image-registry.openshift-image-registry.svc:5000/agentit/pinky:latest
  workspaces:
  - name: shared-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
