apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinky
  namespace: default
  labels:
    app.kubernetes.io/name: pinky
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pinky
  namespace: default
  labels:
    app.kubernetes.io/name: pinky
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pinky
  namespace: default
  labels:
    app.kubernetes.io/name: pinky
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pinky
subjects:
- kind: ServiceAccount
  name: pinky
  namespace: default
