apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pinky.fullname" . }}-api-pdb
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinky-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "pinky.fullname" . }}-web-pdb
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinky-web
