{{- if .Values.redis.deploy }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pinky.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: pinky-redis
    {{- include "pinky.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "pinky.fullname" . }}-redis-headless
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: pinky-redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pinky-redis
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /var/lib/redis/data
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.redis.storage }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinky.fullname" . }}-redis-headless
  labels:
    app.kubernetes.io/name: pinky-redis
    {{- include "pinky.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: pinky-redis
  ports:
    - port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pinky.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: pinky-redis
    {{- include "pinky.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: pinky-redis
  ports:
    - port: 6379
      targetPort: 6379
{{- end }}
