{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinky.fullname" . }}-db-credentials
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ randAlphaNum 24 | b64enc }}
  url: {{ printf "postgresql+asyncpg://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username (randAlphaNum 24) (include "pinky.fullname" .) .Values.postgresql.auth.database | b64enc }}
  url-plain: {{ printf "postgresql://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username (randAlphaNum 24) (include "pinky.fullname" .) .Values.postgresql.auth.database | b64enc }}
{{- end }}
---
{{- if not .Values.encryption.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinky.fullname" . }}-encryption-key
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  key: {{ randAlphaNum 64 | b64enc }}
{{- end }}
---
{{- if or .Values.auth.openshift.clientSecret .Values.auth.oidc.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pinky.fullname" . }}-auth
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.auth.openshift.clientSecret }}
  openshift-client-secret: {{ .Values.auth.openshift.clientSecret | quote }}
  {{- end }}
  {{- if .Values.auth.oidc.clientSecret }}
  oidc-client-secret: {{ .Values.auth.oidc.clientSecret | quote }}
  {{- end }}
{{- end }}
