{{- if .Values.route.enabled }}
{{- $ingressCert := (lookup "v1" "ConfigMap" "openshift-config-managed" "default-ingress-cert") }}
{{- if $ingressCert }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pinky.fullname" . }}-ingress-ca
  labels:
    {{- include "pinky.labels" . | nindent 4 }}
data:
  ingress-ca.crt: |
    {{ index $ingressCert.data "ca-bundle.crt" | nindent 4 }}
{{- end }}
{{- end }}
