INVESTIGATION_QUEUE = "investigation"
REMEDIATION_QUEUE = "remediation"
OBSERVATION_QUEUE = "observation"
PROJECTION_QUEUE = "projection"

ALL_QUEUES = [
    INVESTIGATION_QUEUE,
    REMEDIATION_QUEUE,
    OBSERVATION_QUEUE,
    PROJECTION_QUEUE,
]
