apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: pinky-success-rate
  labels:
    app.kubernetes.io/name: pinky
spec:
  metrics:
  - name: success-rate
    interval: 30s
    count: 5
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-operated.openshift-monitoring.svc:9090
        query: sum(rate(http_requests_total{app="pinky",status=~"2.."}[5m])) / sum(rate(http_requests_total{app="pinky"}[5m]))
    successCondition: result[0] >= 0.95
  - name: error-rate
    interval: 30s
    count: 5
    failureLimit: 2
    provider:
      prometheus:
        address: http://prometheus-operated.openshift-monitoring.svc:9090
        query: sum(rate(http_requests_total{app="pinky",status=~"5.."}[5m])) / sum(rate(http_requests_total{app="pinky"}[5m]))
    successCondition: result[0] <= 0.05
