apiVersion: v1
kind: ConfigMap
metadata:
  name: pinky-rollback-policy
  labels:
    app.kubernetes.io/name: pinky
data:
  auto-rollback: 'true'
  error-budget-threshold: 0.5%
  rollback-window-revisions: '2'
  abort-command: kubectl argo rollouts abort pinky
  undo-command: kubectl argo rollouts undo pinky
  retry-command: kubectl argo rollouts retry rollout pinky
